Repository Electrostatics/apbs-aws, pull requests merged in 2021-06, with the labels that each got.

#114 Release 0.8.4
  ansible/roles/backend/tasks/main.yml
  lambda_services/api_service/api_service.py
  lambda_services/job_service/job_service.py
  lambda_services/job_service/launcher/apbs_runner.py
  lambda_services/job_service/launcher/jobsetup.py
  lambda_services/job_service/launcher/pdb2pqr_runner.py
  lambda_services/job_service/launcher/utils.py
  lambda_services/job_service/launcher/weboptions.py
  lambda_services/tests/apbsjob.py
  lambda_services/tests/jobinterface.py
  lambda_services/tests/pdb2pqrjob.py
  lambda_services/tests/test_job_service.py
  lambda_services/tests/utiljob.py
  requirements-dev.txt
  src/docker/Dockerfile
  src/docker/job_control.py
Labels: release

#115 Fix "invoke method not found" warning and remove redundancy check
  lambda_services/job_service/launcher/pdb2pqr_runner.py
Labels: bug

#118 Adding additional tests to repo
  ansible/roles/backend/tasks/main.yml
  lambda_services/__init__.py
  lambda_services/job_service/job_service.py
  lambda_services/job_service/launcher/utils.py
  lambda_services/tests/__init__.py
  lambda_services/tests/expected_data/template-output.json
  lambda_services/tests/expected_data/test-job_service-output.json
  lambda_services/tests/input_data/1fas.in
  lambda_services/tests/input_data/1fas.pqr
  lambda_services/tests/input_data/apbs-direct-job.json
  lambda_services/tests/input_data/apbs-direct-s3_trigger.json
  lambda_services/tests/input_data/invalid-job.json
  lambda_services/tests/input_data/invalid_job-s3_trigger.json
  lambda_services/tests/input_data/sampleId.in
  lambda_services/tests/input_data/sample_web-pdb2pqr-job.json
  lambda_services/tests/input_data/sample_web-pdb2pqr-s3_trigger.json
  lambda_services/tests/input_data/template-input.json
  lambda_services/tests/input_data/test-job_service-input.json
  lambda_services/tests/test_api_service.py
  lambda_services/tests/test_job_service.py
  requirements-dev.txt
Labels: core

#120 Change default job path to use disk instead of RAM
  src/docker/job_control.py
Labels: bug, deployment

#122 Detect file changes to only build affected files
  build_and_update.sh
  buildspec.yml
  lambda_services/job_service/job_service.py
  lambda_services/job_service/launcher/apbs_runner.py
Labels: deployment
